### ISSUE TITLE
Contributing Guidelines

### ISSUE THREAD

**Issue by allanbreyes** [openai/roboschool#1]
1. Are you accepting open source contributions? I've been wanting to help out, but received no response from a trivial PR on `gym` (https://github.com/openai/gym/pull/561). Will you accept help on this repository?

2. Either way, can you please add a [CONTRIBUTING.md](https://github.com/blog/1184-contributing-guidelines) file? Perhaps it can hint the potential contributor on how to best help; otherwise, maybe it should state whether or not contributions are actually welcomed.

Thanks, and I'm looking forward to tinkering around with this! Looks fantastic thus far. Hope I can help somehow!

**Comment by olegklimov** [comment]
https://github.com/openai/roboschool/wiki/Help-Wanted

https://github.com/openai/roboschool/wiki/Contributing-New-Environments

Hope you find these useful.

**Comment by allanbreyes** [comment]
Thanks!
