### ISSUE TITLE
roboschool installs but no envs load unless in roboschool directory

### ISSUE THREAD

**Issue by zacwellmer** [openai/roboschool#107]
using python3.6 and ubuntu16.04 on amazon's deep learning AMI

I am able to import gym and roboschool w/ no problems. However as soon as I try to import a roboschool env I'm told the env is not registered.

example:
```python
import gym
import roboschool
gym.make('RoboschoolAnt-v1')
```
encounters
```bash
gym.error.UnregisteredEnv: No registered env with id: RoboschoolAnt-v1
```
However, if I move into the roboschool directory then no problems occur. Any ideas as to what is causing this?

**Comment by olegklimov** [comment]
Oh, just look for something silly. Several python installations, you run it from IDE of some kind on not (where you can have different env variables), etc. Only python2 is known to behave differently when you move between directories.
