### ISSUE TITLE
README Update

### ISSUE THREAD

**Issue by rseed42** [openai/roboschool#12]
Hi, just built the environment on Ubuntu 16.04 (Linux Mint 18.1) with Python3, here are two comments:

1.) The Qt OpenGL library is not included in the basic Qt distribution (qtbase5-dev), so please add it to the dependencies list:

`sudo apt install libqt5opengl5-dev`

2) I had to install bullet globally after compiling it, otherwise

`pip3 install -e $ROBOSCHOOL_PATH`

would not work.

Great job with this project, I was really glad to find it before doing something similar with pybullet myself :).

**Comment by olegklimov** [comment]
1. Done. Thanks!

2. Is that still the case? 16.04 should definitively work.
