### ISSUE TITLE
Question on viable alternatives

### ISSUE THREAD

**Issue by kirk86** [openai/roboschool#123]
Hi and thank you for releasing roboschool, this is not an actual issue but rather more of a question. Is there any reason for not using directly one of the other open source alternatives. I understand the issues raised with the not so permissive license of mujoco 👎 . But why not use directly gazebo or opensim, is there any particular reason?

Thanks in advance!

**Comment by olegklimov** [comment]
I all depends on what you want to do. This is collection of RL environments.
