### ISSUE TITLE
Issues with Installation for Anaconda with Python3

### ISSUE THREAD

**Issue by mufeili** [openai/roboschool#13]
In the guide of installation for Mac, Anaconda with Python3, 

```
brew install cmake tinyxml assimp ffmpeg
brew install boost-python --without-python --with-python3 --build-from-source
conda install qt
export PKG_CONFIG_PATH=$(dirname $(dirname $(which python)))/lib/pkgconfig
```

you used brew. I think people rarely use brew and conda together and the underlying python packages are generally different. Would this be a issue? Is there a way to work around brew completely? Thank you.

**Comment by olegklimov** [comment]
It works, that's why it's there.

> Is there a way to work around brew completely? 

Possibly, yes. Quick googling produces some references to boost-python in conda, for example. If you can go through installation with only conda packages, let's post your experience for others to follow.

**Comment by mufeili** [comment]
@olegklimov Hi Oleg, thanks for the reply. I've tried and I think I can install cmake with conda. However it seems there is no way to install tinyxml without brew for Mac OSX(i.e. with pip/conda/from source, etc.)

**Comment by olegklimov** [comment]
This project doesn't need tinyxml. Only Bullet does, and it bundles tinyxml in its repository. You can try again.

**Comment by jtoy** [comment]
Im having trouble getting this to work on 10.10.5 . would love to see non brew instructions as well.

**Comment by cuevasclemente** [comment]
I had problems with this as well following the instructions on the repo on OSX 10.12.6 using conda.

I was able to resolve the problems by adding my conda lib and include directories to the the environment variable $PKG_CONFIG_PATH. I set my PKG_CONFIG_FLAG as:
`"/usr/local/lib/pkgconfig:/usr/local/lib:$HOME/anaconda/lib/pkgconfig"`.

I also downloaded the version of libboost available on meznom's channel (https://anaconda.org/meznom/boost-python) using the command:
` conda install -c meznom boost-python 

After following the homebrew instructions laid out in the README and doing that, I was able to setup locally no problem with `pip install -e $ROBOSCHOOL_PATH`

After this I was able to get it to run without incident.

**Comment by stephenjhansen** [comment]
I am still having some issues and I am not sure if it is a result of brew + Conda. Hopefully I am not polluting the issue thread with too much here.

Any advice would be appreciated.

I am running macOS 10.12.6, I am using a conda environment. I followed the "Mac, Anaconda with Python 3" instructions.

All was well until running pip3:

`Obtaining file:///Users/stephenhansen/Code/DeepRL/gym/roboschool
    Complete output from command python setup.py egg_info:
    found resource files: 185
    running egg_info
    Mac, assumed python3, homebrew branch
    Link against python 3.5
    Slow hardware or software render (no shadows)
    rm -f ../robot-test-tool ../robot-test-tool_d ../cpp_household.so ../cpp_household_d.so  .build-release/physics-bullet.o  .build-release/assets-mesh.o  .build-release/random-world-tools.o  .build-release/render-glwidget.o  .build-release/render-hud.o  .build-release/render-simple.o  .build-release/render-simple-primitives.o  .build-release/test-tool-qt4.o  .build-release/python-binding.o  .build-debug/physics-bullet.o  .build-debug/assets-mesh.o  .build-debug/random-world-tools.o  .build-debug/render-glwidget.o  .build-debug/render-hud.o  .build-debug/render-simple.o  .build-debug/render-simple-primitives.o  .build-debug/test-tool-qt4.o  .build-debug/python-binding.o .generated/*.moc *.ilk *.pdb .build-release/physics-bullet.o.dep .build-release/assets-mesh.o.dep .build-release/random-world-tools.o.dep .build-release/render-glwidget.o.dep .build-release/render-hud.o.dep .build-release/render-simple.o.dep .build-release/render-simple-primitives.o.dep .build-release/test-tool-qt4.o.dep .build-release/python-binding.o.dep .build-debug/physics-bullet.o.dep .build-debug/assets-mesh.o.dep .build-debug/random-world-tools.o.dep .build-debug/render-glwidget.o.dep .build-debug/render-hud.o.dep .build-debug/render-simple.o.dep .build-debug/render-simple-primitives.o.dep .build-debug/test-tool-qt4.o.dep .build-debug/python-binding.o.dep
    rm -rf .generated
    rm -rf .build-debug
    rm -rf .build-release
    Mac, assumed python3, homebrew branch
    Link against python 3.5
    Slow hardware or software render (no shadows)
    mkdir -p .generated
    mkdir -p .build-release
    mkdir -p .build-debug
    gcc -std=c++11 -Wall -Wno-unused-variable -Wno-unused-function -Wno-deprecated-register -fPIC -DBT_USE_DOUBLE_PRECISION -g -O3 -march=native -I/System/Library/Frameworks/OpenGL.framework/Headers `pkg-config --cflags Qt5Widgets Qt5OpenGL assimp python-3.5` -Ibullet_local_install/include -Ibullet_local_install/include/bullet -I/usr/local/include/bullet -c physics-bullet.cpp  -o.build-release/physics-bullet.o -MMD -MF .build-release/physics-bullet.o.dep
    /bin/sh: pkg-config: command not found
    gcc -std=c++11 -Wall -Wno-unused-variable -Wno-unused-function -Wno-deprecated-register -fPIC -DBT_USE_DOUBLE_PRECISION -g -O3 -march=native -I/System/Library/Frameworks/OpenGL.framework/Headers `pkg-config --cflags Qt5Widgets Qt5OpenGL assimp python-3.5` -Ibullet_local_install/include -Ibullet_local_install/include/bullet -I/usr/local/include/bullet -c assets-mesh.cpp  -o.build-release/assets-mesh.o -MMD -MF .build-release/assets-mesh.o.dep
    /bin/sh: pkg-config: command not found
    gcc -std=c++11 -Wall -Wno-unused-variable -Wno-unused-function -Wno-deprecated-register -fPIC -DBT_USE_DOUBLE_PRECISION -g -O3 -march=native -I/System/Library/Frameworks/OpenGL.framework/Headers `pkg-config --cflags Qt5Widgets Qt5OpenGL assimp python-3.5` -Ibullet_local_install/include -Ibullet_local_install/include/bullet -I/usr/local/include/bullet -c random-world-tools.cpp  -o.build-release/random-world-tools.o -MMD -MF .build-release/random-world-tools.o.dep
    /bin/sh: pkg-config: command not found
    gcc -std=c++11 -Wall -Wno-unused-variable -Wno-unused-function -Wno-deprecated-register -fPIC -DBT_USE_DOUBLE_PRECISION -g -O3 -march=native -I/System/Library/Frameworks/OpenGL.framework/Headers `pkg-config --cflags Qt5Widgets Qt5OpenGL assimp python-3.5` -Ibullet_local_install/include -Ibullet_local_install/include/bullet -I/usr/local/include/bullet -c render-glwidget.cpp  -o.build-release/render-glwidget.o -MMD -MF .build-release/render-glwidget.o.dep
    /bin/sh: pkg-config: command not found
    In file included from physics-bullet.cpp:1:
    In file included from ./render-glwidget.h:1:
    ./render-simple.h:6:10: fatal error: 'QtWidgets/QOpenGLWidget' file not found
    #include <QtWidgets/QOpenGLWidget>
             ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    make: *** [.build-release/physics-bullet.o] Error 1
    make: *** Waiting for unfinished jobs....
    In file included from assets-mesh.cpp:1:
    ./render-simple.h:6:10: fatal error: 'QtWidgets/QOpenGLWidget' file not found
    #include <QtWidgets/QOpenGLWidget>
             ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    make: *** [.build-release/assets-mesh.o] Error 1
    In file included from random-world-tools.cpp:3:
    ./render-simple.h:6:10: fatal error: 'QtWidgets/QOpenGLWidget' file not found
    #include <QtWidgets/QOpenGLWidget>
             ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    make: *** [.build-release/random-world-tools.o] Error 1
    In file included from render-glwidget.cpp:2:
    In file included from ./render-glwidget.h:1:
    ./render-simple.h:6:10: fatal error: 'QtWidgets/QOpenGLWidget' file not found
    #include <QtWidgets/QOpenGLWidget>
             ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    make: *** [.build-release/render-glwidget.o] Error 1
    cd /Users/stephenhansen/Code/DeepRL/gym/roboschool/roboschool/cpp-household && make clean && make -j4 dirs  ../cpp_household.so
    
    C++ dependencies for this project are:
    
    bullet
    tinyxml
    boost_python
    assimp
    Qt5
    
    If you see compilation error FIRST THING TO CHECK if pkg-config call was successful.
    Install dependencies that pkg-config cannot find.
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/stephenhansen/Code/DeepRL/gym/roboschool/
`

I have checked to make sure I have installed the C++ dependancies.

`(deeprl2) stephenhansen@Stephens-MacBook-Pro:~/Code/DeepRL/gym$ conda list
# packages in environment at /Users/stephenhansen/anaconda/envs/deeprl2:
#
atari-py                  0.1.1                     <pip>
bleach                    1.5.0                     <pip>
boost-python              1.55.0                        0    meznom
Box2D-kengz               2.3.3                     <pip>
bzip2                     1.0.6                h92991f9_1  
ca-certificates           2017.08.26           ha1e5d58_0  
certifi                   2017.7.27.1      py35h0fdde5e_0  
chardet                   3.0.4                     <pip>
cmake                     3.9.1                hc2f9301_0  
curl                      7.55.1               h7601780_3  
expat                     2.2.4                h8f26bf8_1  
freetype                  2.8                  h143eb01_0  
html5lib                  0.9999999                 <pip>
icu                       58.2                 hea21ae5_0  
idna                      2.6                       <pip>
imageio                   2.2.0                     <pip>
intel-openmp              2018.0.0             hdd0ccc9_7  
jpeg                      9b                   haccd157_1  
Keras                     2.0.8                     <pip>
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                hd939716_3  
libgfortran               3.0.1                h93005f0_2  
libpng                    1.6.32               hce72d48_2  
libssh2                   1.8.0                h1218725_2  
libuv                     1.14.0               h740c2a5_0  
lxml                      4.0.0                     <pip>
Markdown                  2.6.9                     <pip>
mkl                       2018.0.0             hc285769_4  
mujoco-py                 0.5.7                     <pip>
ncurses                   6.0                  ha932d30_1  
numpy                     1.13.1                    <pip>
olefile                   0.44                      <pip>
openssl                   1.0.2l               h57f3a61_2  
pachi-py                  0.0.21                    <pip>
Pillow                    4.2.1                     <pip>
pip                       9.0.1                     <pip>
pip                       9.0.1            py35he52dd69_3  
protobuf                  3.4.0                     <pip>
pyglet                    1.2.4                     <pip>
PyOpenGL                  3.1.0                     <pip>
python                    3.5.4               hf91e954_15  
PyYAML                    3.12                      <pip>
qt                        5.6.2               h9975529_14  
readline                  7.0                  h81b24a6_3  
requests                  2.18.4                    <pip>
rhash                     1.3.5                h3aa0507_1  
scipy                     0.19.1                    <pip>
setuptools                36.5.0           py35h52cde6a_0  
setuptools                36.5.0                    <pip>
six                       1.11.0                    <pip>
sqlite                    3.20.1               h900c3b0_1  
tensorflow                1.3.0                     <pip>
tensorflow-tensorboard    0.1.7                     <pip>
Theano                    0.9.0                     <pip>
tk                        8.6.7                hcdce994_1  
urllib3                   1.22                      <pip>
Werkzeug                  0.12.2                    <pip>
wheel                     0.30.0                    <pip>
wheel                     0.29.0           py35ha7aa5c4_1  
xz                        5.2.3                ha24016e_1  
zlib                      1.2.11               h60db283_1  `

`(deeprl2) stephenhansen@Stephens-MacBook-Pro:~/Code/DeepRL/gym$ brew list
assimp		cmake		gcc		isl		mpfr		pcre		readline	tinyxml		xvid
boost		ctags		gdbm		lame		openssl		python3		sqlite		wget		xz
boost-python	ffmpeg		gmp		libmpc		openssl@1.1	qt		swig		x264
`

**Comment by olegklimov** [comment]
`pkg-config --cflags Qt5Widgets Qt5OpenGL assimp python-3.5` should run.

**Comment by stephenjhansen** [comment]
thank you @olegklimov. After running pkg-config and the following, I was able to run `pip3 install -e $ROBOSCHOOL_PATH` without errors.

although trivial, In case someone else comes across this in a search here are the other things I did get it to install.

> sudo chown -R $USER ~/anaconda/lib/python3.6

I also had to install a few packages I hadn't installed in that environment earlier

> conda install numpy six

I am now having trouble accessing the environments that ship with roboschool.

When I try to execute the suggested test of the flagrun I get a key error:

> python $ROBOSCHOOL_PATH/agent_zoo/RoboschoolHumanoidFlagrun_v0_2017may.py
> [2017-10-01 23:32:02,421] Making new env: RoboschoolHumanoidFlagrun-v1
> Traceback (most recent call last):
>   File "/Users/stephenhansen/Code/DeepRL/gym/gym/envs/registration.py", line 140, in spec
>     return self.env_specs[id]
> KeyError: 'RoboschoolHumanoidFlagrun-v1'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/stephenhansen/Code/DeepRL/gym/roboschool/agent_zoo/RoboschoolHumanoidFlagrun_v0_2017may.py", line 492, in <module>
>     demo_run()
>   File "/Users/stephenhansen/Code/DeepRL/gym/roboschool/agent_zoo/RoboschoolHumanoidFlagrun_v0_2017may.py", line 23, in demo_run
>     env = gym.make("RoboschoolHumanoidFlagrun-v1")
>   File "/Users/stephenhansen/Code/DeepRL/gym/gym/envs/registration.py", line 164, in make
>     return registry.make(id)
>   File "/Users/stephenhansen/Code/DeepRL/gym/gym/envs/registration.py", line 121, in make
>     spec = self.spec(id)
>   File "/Users/stephenhansen/Code/DeepRL/gym/gym/envs/registration.py", line 150, in spec
>     raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
> gym.error.UnregisteredEnv: No registered env with id: RoboschoolHumanoidFlagrun-v1

I am not sure how related this comment is to the intent of this issue (Conda and Brew dependancies) I would be happy to make a new issue if you think it necessary.

**Comment by stephenjhansen** [comment]
To clarify the problem I am still having as mentioned in the previous post.

- roboschool installs without errors
- I can run import roboschool without errors
- I cannot run any of the environments that ship with roboschool 
  e.g. `env2 = gym.make('RoboschoolHumanoidFlagrun-v1')` returns
  gym.error.UnregisteredEnv: No registered env with id: RoboschoolHumanoidFlagrun-v1

Here are the install steps I have completed so far:

1. Mac, Anaconda with Python 3 instructions from README
2. Compile and install bullet instructions from README
3.` sudo chown -R $USER ~/anaconda/lib/python3.6` to prevent ownership issues
4. `pkg-config --cflags Qt5Widgets Qt5OpenGL assimp python-3.5 `as suggested by @olegklimov 

I am running on macOS 10.12.6

Any advice is appreciated. Let me know if I should create a new issue - sorry if I have polluted this thread with unrelated comments.

**Comment by olegklimov** [comment]
Oh even if it is like you describe, should be easy to debug. Just with `print`s is alright. Put one in roboschool __init__, put another in Gym.

**Comment by bnjasim** [comment]
I got the a similar error while `pip install -e $ROBOSCHOOL_PATH`

`pip install -e $ROBOSCHOOL_PATH
Obtaining file:///Users/bnjasim/Desktop/RL/roboschool
    Complete output from command python setup.py egg_info:
    /Users/bnjasim/Desktop/RL/roboschool/roboschool/cpp-household/bullet_local_install/lib
    ******************************
    
    ['libBullet2FileLoader', 'libBulletCollision', 'libBullet3Collision', 'libBulletDynamics', 'libBullet3Common', 'libBulletInverseDynamics', 'libBullet3Dynamics', 'libBulletSoftBody', 'libBullet3Geometry', 'libLinearMath', 'libBullet3OpenCL_clew', 'libPhysicsClientC_API']
    ******************************
    
    found resource files: 185
    running egg_info
    Mac, assumed python3, homebrew branch
    Link against python 3.6
    Slow hardware or software render (no shadows)
    rm -f ../robot-test-tool ../robot-test-tool_d ../cpp_household.so ../cpp_household_d.so  .build-release/physics-bullet.o  .build-release/assets-mesh.o  .build-release/random-world-tools.o  .build-release/render-glwidget.o  .build-release/render-hud.o  .build-release/render-simple.o  .build-release/render-simple-primitives.o  .build-release/test-tool-qt4.o  .build-release/python-binding.o  .build-debug/physics-bullet.o  .build-debug/assets-mesh.o  .build-debug/random-world-tools.o  .build-debug/render-glwidget.o  .build-debug/render-hud.o  .build-debug/render-simple.o  .build-debug/render-simple-primitives.o  .build-debug/test-tool-qt4.o  .build-debug/python-binding.o .generated/*.moc *.ilk *.pdb .build-release/physics-bullet.o.dep .build-release/assets-mesh.o.dep .build-release/random-world-tools.o.dep .build-release/render-glwidget.o.dep .build-release/render-hud.o.dep .build-release/render-simple.o.dep .build-release/render-simple-primitives.o.dep .build-release/test-tool-qt4.o.dep .build-release/python-binding.o.dep .build-debug/physics-bullet.o.dep .build-debug/assets-mesh.o.dep .build-debug/random-world-tools.o.dep .build-debug/render-glwidget.o.dep .build-debug/render-hud.o.dep .build-debug/render-simple.o.dep .build-debug/render-simple-primitives.o.dep .build-debug/test-tool-qt4.o.dep .build-debug/python-binding.o.dep
    rm -rf .generated
    rm -rf .build-debug
    rm -rf .build-release
    Mac, assumed python3, homebrew branch
    Link against python 3.6
    Slow hardware or software render (no shadows)
    mkdir -p .generated
    mkdir -p .build-release
    mkdir -p .build-debug
    gcc -std=c++11 -Wall -Wno-unused-variable -Wno-unused-function -Wno-deprecated-register -fPIC -DBT_USE_DOUBLE_PRECISION -g -O3 -march=native -I/System/Library/Frameworks/OpenGL.framework/Headers `pkg-config --cflags Qt5Widgets Qt5OpenGL assimp python-3.6` -Ibullet_local_install/include -Ibullet_local_install/include/bullet -I/usr/local/include/bullet -c physics-bullet.cpp  -o.build-release/physics-bullet.o -MMD -MF .build-release/physics-bullet.o.dep
    gcc -std=c++11 -Wall -Wno-unused-variable -Wno-unused-function -Wno-deprecated-register -fPIC -DBT_USE_DOUBLE_PRECISION -g -O3 -march=native -I/System/Library/Frameworks/OpenGL.framework/Headers `pkg-config --cflags Qt5Widgets Qt5OpenGL assimp python-3.6` -Ibullet_local_install/include -Ibullet_local_install/include/bullet -I/usr/local/include/bullet -c assets-mesh.cpp  -o.build-release/assets-mesh.o -MMD -MF .build-release/assets-mesh.o.dep
    gcc -std=c++11 -Wall -Wno-unused-variable -Wno-unused-function -Wno-deprecated-register -fPIC -DBT_USE_DOUBLE_PRECISION -g -O3 -march=native -I/System/Library/Frameworks/OpenGL.framework/Headers `pkg-config --cflags Qt5Widgets Qt5OpenGL assimp python-3.6` -Ibullet_local_install/include -Ibullet_local_install/include/bullet -I/usr/local/include/bullet -c random-world-tools.cpp  -o.build-release/random-world-tools.o -MMD -MF .build-release/random-world-tools.o.dep
    gcc -std=c++11 -Wall -Wno-unused-variable -Wno-unused-function -Wno-deprecated-register -fPIC -DBT_USE_DOUBLE_PRECISION -g -O3 -march=native -I/System/Library/Frameworks/OpenGL.framework/Headers `pkg-config --cflags Qt5Widgets Qt5OpenGL assimp python-3.6` -Ibullet_local_install/include -Ibullet_local_install/include/bullet -I/usr/local/include/bullet -c render-glwidget.cpp  -o.build-release/render-glwidget.o -MMD -MF .build-release/render-glwidget.o.dep
    gcc -std=c++11 -Wall -Wno-unused-variable -Wno-unused-function -Wno-deprecated-register -fPIC -DBT_USE_DOUBLE_PRECISION -g -O3 -march=native -I/System/Library/Frameworks/OpenGL.framework/Headers `pkg-config --cflags Qt5Widgets Qt5OpenGL assimp python-3.6` -Ibullet_local_install/include -Ibullet_local_install/include/bullet -I/usr/local/include/bullet -c render-hud.cpp  -o.build-release/render-hud.o -MMD -MF .build-release/render-hud.o.dep
    gcc -std=c++11 -Wall -Wno-unused-variable -Wno-unused-function -Wno-deprecated-register -fPIC -DBT_USE_DOUBLE_PRECISION -g -O3 -march=native -I/System/Library/Frameworks/OpenGL.framework/Headers `pkg-config --cflags Qt5Widgets Qt5OpenGL assimp python-3.6` -Ibullet_local_install/include -Ibullet_local_install/include/bullet -I/usr/local/include/bullet -c render-simple.cpp  -o.build-release/render-simple.o -MMD -MF .build-release/render-simple.o.dep
    gcc -std=c++11 -Wall -Wno-unused-variable -Wno-unused-function -Wno-deprecated-register -fPIC -DBT_USE_DOUBLE_PRECISION -g -O3 -march=native -I/System/Library/Frameworks/OpenGL.framework/Headers `pkg-config --cflags Qt5Widgets Qt5OpenGL assimp python-3.6` -Ibullet_local_install/include -Ibullet_local_install/include/bullet -I/usr/local/include/bullet -c render-simple-primitives.cpp  -o.build-release/render-simple-primitives.o -MMD -MF .build-release/render-simple-primitives.o.dep
    gcc -std=c++11 -Wall -Wno-unused-variable -Wno-unused-function -Wno-deprecated-register -fPIC -DBT_USE_DOUBLE_PRECISION -g -O3 -march=native -I/System/Library/Frameworks/OpenGL.framework/Headers `pkg-config --cflags Qt5Widgets Qt5OpenGL assimp python-3.6` -Ibullet_local_install/include -Ibullet_local_install/include/bullet -I/usr/local/include/bullet -c python-binding.cpp  -o.build-release/python-binding.o -MMD -MF .build-release/python-binding.o.dep
    render-simple.cpp:7:10: fatal error: 'gl3.h' file not found
    #include <gl3.h>
             ^~~~~~~
    1 error generated.
    make: *** [.build-release/render-simple.o] Error 1
    make: *** Waiting for unfinished jobs....
    cd /Users/bnjasim/Desktop/RL/roboschool/roboschool/cpp-household && make clean && make -j4 dirs  ../cpp_household.so
    
    C++ dependencies for this project are:
    
    bullet
    tinyxml
    boost_python
    assimp
    Qt5
    
    If you see compilation error FIRST THING TO CHECK if pkg-config call was successful.
    Install dependencies that pkg-config cannot find.
    `

It looks like almost impossible for me to get the roboschool running on my mac. Any help would be appreciated.

**Comment by YunqiuXu** [comment]
@stephenjhansen have you solved it? Same problem when installing it with ubuntu 16.04 and anaconda 3
