### ISSUE TITLE
Can you please create a docker image for OSX and Linux

### ISSUE THREAD

**Issue by FitMachineLearning** [openai/roboschool#130]
Hi,

It would be great if a docker image could be created for those two environments.
It would 
1) significantly increase adoption for RoboSchool
2) reduce support  calls/ issues related to deployment, installs, and dev machine related configuration deviations.

Fit

**Comment by pzhokhov** [comment]
@doviettung96's Dockerfile for now lives in a branch https://github.com/openai/roboschool/tree/pr168.
With the release of binary wheels the default installation process is a simple as `pip install roboschool` (provided there is a binary wheel for your system config), so Dockerfiles seem unnecessary. Closing this.

**Comment by doviettung96** [comment]
Yeah. I have also realized that the binary installation is better. I have created the Dockerfile before it was released. For now, it is unnecessary. Thanks.
