### ISSUE TITLE
Details observation and action for Atlas

### ISSUE THREAD

**Issue by trminh89** [openai/roboschool#135]
What are the details of observation and action in Atlas robot model? From the code, the observation shape is (70,) and action shape is (30, ). Do we have a description of the model? I can find the detailed in [Humanoid model](https://github.com/openai/gym/wiki/Humanoid-V1), but there is no information for Atlas.

**Comment by olegklimov** [comment]
Hi. You can discover it yourself. Turn off gravity, apply actions one by one, observe robot reaction. Another option is robot testing tool (included).
