### ISSUE TITLE
Camera Following Agent

### ISSUE THREAD

**Issue by mahiuchun** [openai/roboschool#143]
Running demos like the following:
`python $ROBOSCHOOL_PATH/agent_zoo/demo_race2.py`

It appears that the camera position for rendering is, for the most part, fixed.
Thus, the agent behavior cannot be observed (since they run out of rendered plane quickly).
Some mouse movement allows rotation and zooming but it still feels a bit awkward. 

If automatic following is somewhat difficult could we make it possible to enable ASDW control as currently disabled in the following code?
https://github.com/openai/roboschool/blob/master/roboschool/cpp-household/render-glwidget.cpp#L371

**Comment by olegklimov** [comment]
Right mouse button allows to move scene around. Yes you can uncomment asdw and see what happens.
