### ISSUE TITLE
Cannot Import roboschool

### ISSUE THREAD

**Issue by dhanush987** [openai/roboschool#148]
I am getting the below error while trying to import roboschool

Python 3.7.0 (default, Jul 23 2018, 20:22:55) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import roboschool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dhdharma/GitHub/roboschool/roboschool/__init__.py", line 1, in <module>
    from gym.envs.registration import register
ModuleNotFoundError: No module named 'gym'
>>> 

Installed

**Comment by olegklimov** [comment]
Means you have gym installed to another version of python
