### ISSUE TITLE
Do I need to use RoboschoolHumanoid-v0's pretrained model when training RoboschoolHumanoidFlagrunHarder-v0?

### ISSUE THREAD

**Issue by Megatron2032** [openai/roboschool#150]
mean reward has been maintained at around 500 when i use baseline(ppo2) to train RoboschoolHumanoidFlagrunHarder-v0 without pretrained model.But the RoboschoolHumanoid-v0 is good.

**Comment by olegklimov** [comment]
The answer is no. I know people why succeeded training Harder from scratch using exactly ppo2. (with some minor modifications I don't know exactly about)
