### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by rnunziata** [openai/roboschool#156]
It is not clear after  following the instruction listed here

with   ROBOSCHOOL_PATH =..local directory named roboschool

```
git clone https://github.com/olegklimov/bullet3 -b roboschool_self_collision
mkdir bullet3/build
cd    bullet3/build
cmake -DBUILD_SHARED_LIBS=ON -DUSE_DOUBLE_PRECISION=1 -DCMAKE_INSTALL_PREFIX:PATH=$ROBOSCHOOL_PATH/roboschool/cpp-household/bullet_local_install -DBUILD_CPU_DEMOS=OFF -DBUILD_BULLET2_DEMOS=OFF -DBUILD_EXTRAS=OFF  -DBUILD_UNIT_TESTS=OFF -DBUILD_CLSOCKET=OFF -DBUILD_ENET=OFF -DBUILD_OPENGL3_DEMOS=OFF ..
make -j4
sudo make install
cd ../..
```
and then issuing

`pip3 install -e $ROBOSCHOOL_PATH  `

which must be issued from built3 directory.

that the repository

`https://github.com/openai/roboschool.git`

containing the demos is not installed  so that 
`python $ROBOSCHOOL_PATH/agent_zoo/demo_race2.py`
can not be found.

The instruction seem to be missing something....is it possible to fix this in the readme and give the solution here. Right now I have two directories one bullet3 and one roboschool.  What is the next step to the install.

**Comment by olegklimov** [comment]
great!
