### ISSUE TITLE
roboschool2

### ISSUE THREAD

**Issue by andri27-ts** [openai/roboschool#159]
Hi,
is there some news about roboschool2? Which will be the 'different priorities' you are working on?
Thanks

**Comment by olegklimov** [comment]
Well it stuck a bit because we find continuous control not to be a bottleneck. I think it will make another big stride forward once more of high-level thinking is figured out.

**Comment by TomorrowIsAnOtherDay** [comment]
Hi, any news now?

**Comment by michtesar** [comment]
I would give you any hand. What is the status? Thanks :-)
