### ISSUE TITLE
env.reset() not working

### ISSUE THREAD

**Issue by agrib** [openai/roboschool#174]
After installing roboschool with pip in a conda environment on ubuntu (using python 3.6.8) .
env.reset() not working.
Getting error 
**Illegal instruction (core dumped)**

or 
when running demo_race2.py in line 43
 when we call stadium.episode_restart(),
then in scene_stadium.py line 14 self.cpp_world.load_thingy
got the same error

**Comment by xht033** [comment]
I got the same issue. Have you solved this?

**Comment by teju81** [comment]
I get this error when I run env.reset(). I use Python 3.7.1

**Comment by tamirblum** [comment]
I also have this issue (did not use Conda). Did anyone find the reason? Using python 3.6
