### ISSUE TITLE
ImportError: libQt5OpenGL.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by joshua-matt** [openai/roboschool#212]
When I try to run `python test_manual.py`, I get the above error message, which is thrown in importing `cpp_household_d` on line 11 of `scene_abstract.py`. I see that the sought file is present in the `.libs` folder. I'm using Ubuntu 20.04; is there some package I need to install?

**Comment by TheCrazyT** [comment]
could be another missing dependency.
I would do:
`ldd libQt5OpenGL.so.5`
Inside the .libs folder to see if it shows any missing files.

**Comment by joshua-matt** [comment]
Here is the output. What do I do with this information?
![image](https://user-images.githubusercontent.com/29611603/124967008-895ed680-dfe9-11eb-80fa-d86bbed910b8.png)

**Comment by TheCrazyT** [comment]
Looks ok, else it won't show the paths.
Could you do the same for cpp_household_d.so please?

(If path is missing there you probably need to add the path of the .libs folder to the LD_LIBRARY_PATH environment variable, but not shure if it is really needed.
I think "pip" should normaly install those libraries in a system folder, if I remember correctly.)

**Comment by joshua-matt** [comment]
Adding the `.libs` folder to LD_LIBRARY_PATH (in /etc/environment) fixed the problem! If anyone else has this issue, remember you have to log out and log back in to have changes to environment variables apply. I also needed the gym version to be 0.15.4.
