### ISSUE TITLE
Issue running the Demo

### ISSUE THREAD

**Issue by KarimHassanieh** [openai/roboschool#22]
Hi after compiling and installing the code I am still unable to run the demo version ive followed the readme instruction word by word can anyone help ? below is the error
![screenshot from 2017-06-08 09-03-57](https://user-images.githubusercontent.com/25553965/26914391-99c70982-4c29-11e7-9f4b-6d771303f335.png)

**Comment by cjjeakle** [comment]
If you have python 2.7 on your machine (note: nearly all flavors of Ubuntu except server do by default), you probably need to invoke the script using `python3` instead of `python`.

**Comment by KarimHassanieh** [comment]
issue resolved i had to install gym using pip3..now works well

**Comment by olegklimov** [comment]
Great!
