### ISSUE TITLE
composeAndFlush: makeCurrent() failed

### ISSUE THREAD

**Issue by Simplex2** [openai/roboschool#28]
I installed as the instructions in ubuntu 16.10, but when I try to run the pretrained agent, I got this message continually. 

`composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
`
What's the problem?

**Comment by olegklimov** [comment]
Something similar fixed in #2, please take a look.

**Comment by olegklimov** [comment]
Stalled issue, please let me know if there's something we can fix.

**Comment by toothlessdragon** [comment]
I took a look at #2 but I still didn't see how to fix ```composeAndFlush: makeCurrent() failed```.

I'm on ubuntu 16.04 (azure VM) trying to see the video over X11 forwarding.  I set up my system using this script:

```
#!/bin/sh
sudo apt-get update;
sudo apt-get upgrade -y;
sudo apt-get install -y cmake ffmpeg pkg-config qtbase5-dev libqt5opengl5-dev libassimp-dev libpython3.5-dev libboost-python-dev libtinyxml-dev;
git clone https://github.com/openai/roboschool.git ~/roboschool;
cd ~/roboschool;
ROBOSCHOOL_PATH=$(pwd);
cd ..;
git clone https://github.com/olegklimov/bullet3 -b roboschool_self_collision;
mkdir bullet3/build;
cd bullet3/build;
cmake -DBUILD_SHARED_LIBS=ON -DUSE_DOUBLE_PRECISION=1 -DCMAKE_INSTALL_PREFIX:PATH=$ROBOSCHOOL_PATH/roboschool/cpp-household/bullet_local_install -DBUILD_CPU_DEMOS=OFF -DBUILD_BULLET2_DEMOS=OFF -DBUILD_EXTRAS=OFF  -DBUILD_UNIT_TESTS=OFF -DBUILD_CLSOCKET=OFF -DBUILD_ENET=OFF -DBUILD_OPENGL3_DEMOS=OFF ..;
make -j4;
make install;
cd ../..;
sudo apt-get install -y python3-pip;
pip3 install --upgrade pip;
sudo -H pip3 install pyopengl;
pip3 install -e $ROBOSCHOOL_PATH;
```

**Comment by PandaYue99** [comment]
I am getting the same error message of composeAndFlush:makeCurrent() failed  
I am on Ubuntu 16.04 conda+ gym+tensorflow installed, during installation, no error message occurred.

**Comment by ramilmsh** [comment]
Any updates?

**Comment by codydg** [comment]
Per [this user's comment](https://github.com/openai/roboschool/issues/2#issuecomment-456541588) on another issue, if you're using Windows 10's WSL and XLaunch, Make sure to start XLaunch in the "Single large window" mode, not the default "Multiple Windows" mode. This fixed the issue for me.

EDIT:
If you go to the link above, there is another comment directly below it that gives help for those 
 "Using the docker container on Windows 10 (with docker in "Linux Containers" mode) and VcXsrv/XLaunch"
