### ISSUE TITLE
Household and Robot Models

### ISSUE THREAD

**Issue by ashwinreddy** [openai/roboschool#30]
Hello,

I was looking around the repo and saw the `roboschool/models_robot` and `roboschool/models_household` folders. I was wondering how I would view these models in Bullet/MuJoCo simulation since they don't seem to have environments connected to them. I am interested in getting robots to do household tasks, so if an environment doesn't currently exist, I might be willing to build it myself if it isn't too complicated.

**Comment by olegklimov** [comment]
It is complicated :)

This project will hopefully get to these tasks.

**Comment by olegklimov** [comment]
Stalled issue, let's close this. And we have Atlas in v1.1.
