### ISSUE TITLE
How can we train the atlas robot to walk

### ISSUE THREAD

**Issue by tianna1121** [openai/roboschool#38]
hi, openai
   How can we train the atlas robot to walk? Thanks

**Comment by tianna1121** [comment]
I notice that the roboschool include a model of atlas robot. I just want to know how to use that model.

**Comment by olegklimov** [comment]
It doesn't work well yet :(

**Comment by olegklimov** [comment]
Yes we can, see v1.1

**Comment by benelot** [comment]
Where is version 1.1? Can you link to it in some way?
