### ISSUE TITLE
Can I load URDF robots?

### ISSUE THREAD

**Issue by tjacobs** [openai/roboschool#5]
How can I load URDF model robots (i.e. ones with STL models as parts), such as Fetch and Atlas, and my own? Is there a demo script for these currently?

**Comment by tkelestemur** [comment]
Same here, is it possible to do that?

**Comment by benelot** [comment]
Bullet Physics can do this out of the box, but I am not sure if it is accessible through roboschool.

**Comment by olegklimov** [comment]
A word of advice. The focus of this project is research. If you want realistic simulation for realistic robots, you're better off with ROS and Gazebo and V-REP. Use this project for simplified environments to study or improve learning methods you use.

That said, there are Atlas and Fetch model in this repository. Atlas works with modifications I have in the works and without self-collision, Fetch doesn't work yet. And no, these models don't work in Bullet and pybullet. It's doable, but a bit more work is required.

For Atlas and Fetch environments to officially appear here, first thing to figure out is what set of tasks will be most useful. Once again, the focus is research.

**Comment by tjacobs** [comment]
Thanks Oleg, yep, this is just for some basic simulation of joint movements. I've used Gazebo but it's overkill for what I need and a pain to set up. I'm simulating my robot which is described in URDF format, and it's currently being simulated in Bullet via pybullet fine, I'm just wondering how to bring it over to the nice roboschool UI, and then I can start trying out some walking policies as well.

I'll await your work on the Atlas loading, thanks!

**Comment by olegklimov** [comment]
If you know where to modify your own robot, you have good chances to have it working in Roboschool. Compared to pybullet, python binding here is arguably better (objects are objects, not int handles), but still not obvious choice. It will take bigger environments that having C++ part will show advantages.

**Comment by olegklimov** [comment]
Let's keep it open for others to see.

**Comment by olegklimov** [comment]
We have Atlas in v1.1. Let's close this.

**Comment by tjacobs** [comment]
Nice! Thanks! I'll try him out.

**Comment by benelot** [comment]
How do I get version 1.1?

**Comment by olegklimov** [comment]
It's there.

**Comment by ricardotellez** [comment]
Hi tjacobs.
I think that this tool can be useful for what you need: [Ros Development Studio](http://rds.theconstructsim.com)
It is a web development environment for ROS including already working simulations. No need to install or configure anything, and you can use any computer to program and test in ROS.

Recently we included OpenAI Gym support. You can check how it works here: https://youtu.be/0sNWqtCGTAQ

Also if you need to learn more about how to use OpenAI with ROS and Gazebo sims I would recommend you this tutorial: https://youtu.be/o9FpZ1QQqcc

Finally, if you wan to know more about URDF robots, try this tutorial: https://youtu.be/UUwHK5ONTAQ

Hope it helps.

**Comment by meppe** [comment]
Hi, 
I was trying to port the Hindsight Experience Replay (HER) experiments with the Fetch robot from the mujoco-based simulation of OpenAI baselines to roboschool, but this turned out to be more complicated than expected. I would highly appreciate an integration!

**Comment by benelot** [comment]
Since roboschool is starting to age as it is clamped to a certain version
of bullet, I would recommend to integrate it with pybullet, which features
the same mujoco ports as roboschool but is much more actively maintained.
Check out pybullet on github.
