### ISSUE TITLE
RoboschoolHumanoid has negative rewards

### ISSUE THREAD

**Issue by garymcintire** [openai/roboschool#50]
I couldn't get the humanoid to learn so investigated and found that the rewards seem to be between -15 and 0. Of course this doesn't work with variable horizon episodic RL because the easiest way to get a higher cumulative reward is to just shorten the episodes.
I made it train by adding 15 to every reward but it only learned to have long episodes, didn't move forward. I am currently testing by adding only 5 each step.
But, openai published many results with it.
Is the current master broken or could something be amiss with my setup? Anybody else get it to train without modifying?

**Comment by olegklimov** [comment]
Check out your noise level in a policy. It may be way, way larger than you want, also producing electricity cost.
