### ISSUE TITLE
Install problems due to missing packages

### ISSUE THREAD

**Issue by zacwellmer** [openai/roboschool#58]
After attempting to install roboschool in the final step I'm receiving a few errors that look like the following:
```bash
Package Qt5Widgets was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5Widgets.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5Widgets' found
```

I'm not sure where I'm supposed to be grabbing these .pc files from.

**Comment by locke-phan** [comment]
@zacwellmer what platform are you trying to compile it for? did the compilation process succeed?

**Comment by panda1221** [comment]
Hi all,
I have the same issue.
I use Mac os to build it.
Who can help on this issue?

Thank you

**Comment by olegklimov** [comment]
> supposed to be grabbing these .pc files from.

`PKG_CONFIG_PATH` does that. Please see if instructions in README help. Check the .pc files are at location that `PKG_CONFIG_PATH` points to.
