### ISSUE TITLE
File 'setup.py' not found.

### ISSUE THREAD

**Issue by buzzo123** [openai/roboschool#70]
pip3 install -e $ROBOSCHOOL_PATH
Directory '/home/buzzo/roboschool' is not installable. File 'setup.py' not found.

**Comment by XinyiYS** [comment]
I have got the same problem, how did you  resolve it, buzzo123?

**Comment by imperator-maximus** [comment]
same problem here... what is the solution?

**Comment by imperator-maximus** [comment]
ok that is what I found so far:
1. clone roboschool git repro first so pip3 install -e $ROBOSCHOOL_PATH works without any problems
2. install OpenAI gym 
now I am getting a 
ImportError: No module named 'roboschool'
error... any idea?

**Comment by imperator-maximus** [comment]
I found solution:
pip install -e .
in roboschool folder and so everything works.
So at all:
1. git clone roboschool and set that path in $ROBOSCHOOL_PATH
2. do everything from installation instructions
3. pip3 install -e $ROBOSCHOOL_PATH
4. cd $ROBOSCHOOL_PATH; pip install -e .
