### ISSUE TITLE
Can I use xacro file?

### ISSUE THREAD

**Issue by k123jack** [openai/roboschool#71]
Can I directly open a xacro file using gym_urdf_robot_env?

**Comment by olegklimov** [comment]
No. Also, xacro and other ROS machinery is complicated and poorly thought out. So I don't think we need more support for it. For instance, Mujoco XMLs are shorter and better and more capable, and you don't see DLL loads there.

**Comment by k123jack** [comment]
But most of the mujoco XMLs from here :  http://www.mujoco.org/forum/index.php?resources/categories/models.3/   are not supported too.

**Comment by olegklimov** [comment]
Right, this project is not a mujoco emulator.

**Comment by k123jack** [comment]
So, it also doesn't support friction or etc, and we can not train grasping.

**Comment by olegklimov** [comment]
Of course there is friction, otherwise robots will be falling all the time, you can even control it from .xml I believe. If your effort is something serious, you should talk to Erwin about friction and the state of it in Bullet. Pretty good according to demos you may find in Bullet.

**Comment by k123jack** [comment]
Thanks,  I really need to know about the state and friction and to improve the architecture of the network.
