### ISSUE TITLE
Stuck joint cost for Reacher environment

### ISSUE THREAD

**Issue by zhangwj618** [openai/roboschool#81]
The 'stuck joint cost' contributes to the reward function of the Reacher environment and is defined as shown below in file _gym_reacher.py_. Apparently it serves to penalize the case when the second segment of the robot arm is stuck at the center.
`stuck_joint_cost = -0.1 if np.abs(np.abs(self.gamma)-1) < 0.01 else 0.0`

Nevertheless, when I try to sample rollouts with constant actions of 1 (similar results for actions of -1) so that the second segment is stuck, the second joint has the following final values (10 samples are shown):
[ 1.15 ,  1.038,  1.116,  1.065,  1.162,  1.045,  1.067,  1.126, 1.12 ,  1.072].

Hence, the 'stuck joint cost' is in fact not working as intended. One possible fix I can think of is to change the line to:
`stuck_joint_cost = -0.1 if np.abs(self.gamma) > 0.99 else 0.0`

**Comment by olegklimov** [comment]
Yeah that's quite reasonable, joint goes beyond limit. But don't think it plays any role in practice. +1 action is maximum torque and it's pretty high, once you start optimizing your network is unlikely to do that. I'm too lazy to test all learning again with the change you propose, but of course it's reasonable thing to do for your learning if you need it.
