### ISSUE TITLE
Trajectory-centric MuJoCo tasks?

### ISSUE THREAD

**Issue by hzyjerry** [openai/roboschool#84]
In the roboschool roadmap, it mentions "trajectory-centric fragile MuJoCo tasks". Could you help explain the statement, or give some pointer to it? 

Thanks

**Comment by olegklimov** [comment]
Oh that's very simple. If you have single task that is mostly deterministic, you'll see policy collapse to very narrow set of trajectories, and policy will be incompetent outside of this narrow beam. Instead, you can start randomly, push robot randomly, execute random tasks, and be competent in more of the state space.

**Comment by hzyjerry** [comment]
Thanks!
