### ISSUE TITLE
E: Unable to locate package setup

### ISSUE THREAD

**Issue by DaveRondini** [openai/roboschool#85]
I tried a simple 'hello world' to make sure my syntax was correct. What am I doing wrong? It does this with every single *.py file in roboschool and gym. (FYI- I only included below for demonstrative purposes. I had already installed hello world prior to this, that's why it says there's no update)

dave@dave-VirtualBox:~$ sudo su
[sudo] password for dave: 
root@dave-VirtualBox:/home/dave# cd hello-master
root@dave-VirtualBox:/home/dave/hello-master# apt install hello
Reading package lists... Done
Building dependency tree       
Reading state information... Done
hello is already the newest version (2.10-1build1).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
root@dave-VirtualBox:/home/dave/hello-master# hello
Hello, world!
root@dave-VirtualBox:/home/dave/hello-master# cd ..
root@dave-VirtualBox:/home/dave# cd roboschoolM
root@dave-VirtualBox:/home/dave/roboschoolM# apt install setup
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package setup
root@dave-VirtualBox:/home/dave/roboschoolM# ^C
root@dave-VirtualBox:/home/dave/roboschoolM#

**Comment by olegklimov** [comment]
python2 can give you those.

That is, you can get different results from commands you type, depending on what files and dirs you have in current directory. Solution is "use python 3".
