### ISSUE TITLE
Symmetry of Ant

### ISSUE THREAD

**Issue by GarrettAndersen** [openai/roboschool#89]
I am trying to train the ant to walk in the y-direction (from scratch). It seems to be much more difficult to train than walking in the x-direction (I am using PPO from baselines). 

Is there any asymmetry in the environment that could explain this?

**Comment by olegklimov** [comment]
Er... Maybe. From quick look at .xml, I don't see any asymmetry. Probably it's even more fun when your robot is not perfect, right?
