### ISSUE TITLE
load new weights files

### ISSUE THREAD

**Issue by wenyijiang** [openai/roboschool#91]
Hi!
    In the agent_zoo directory there are some files about weights. I want to use my weights that trained by the tensorflow about  baselines.ddpg algorithm but there are some issues. I want to know whether I can change  my weights and load it .and how did  you get the weights file  
    There is the error message:
    InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [15,64] rhs shape= [11,64]
     [[Node: save/Assign_15 = Assign[T=DT_FLOAT, _class=["loc:@critic/dense/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](critic/dense/kernel, save/RestoreV2_15)]]

**Comment by olegklimov** [comment]
Sorry this looks to be a problem with your model and code, not a problem in this project.
