### ISSUE TITLE
what is human data format

### ISSUE THREAD

**Issue by xingxing1** [openai/roboschool#96]
what is meaning weights_dense1_w in RoboschoolWalder2d_vo_2017may.py,I want use my data,but i don't know data format

**Comment by olegklimov** [comment]
`_w` is matrix, `_b` is bias.

**Comment by xingxing1** [comment]
I mean _w matrix data format,such as column or row,why it is 22 row 128 column,i dont understand the mean that represent,I can't find any introduce document.

**Comment by olegklimov** [comment]
It's implemented using neural networks. Please read about how they work.

**Comment by xingxing1** [comment]
If I want training my data using neural networks,I should know what is standard data,I have data set including joint angle,step space,angular velocity etc.i have human gate data,but I can’t connect it with matrix that you said, I don’t know what model of human model you use. Whether or not i have misconception about roboschool.
